/**
 * App version + update-feed helpers (server-side).
 *
 * Phase 1 of the Vek-Snap update system: the app can tell the user when a newer
 * release exists by fetching a small public `latest.json` feed. This module is
 * SERVER-ONLY (uses fs): the browser learns the version via /api/app-update,
 * never by bundling package.json.
 */
import fs from "fs";
import path from "path";

/**
 * Where the public version feed lives. Overridable via env for staging/testing.
 * The feed is generated by
 * VEK-SNAP_Deployment_Plan/Version_Tracking/gen-latest-json.mjs and hosted at a
 * static URL (e.g. the site or a GitHub release asset).
 */
export const UPDATE_FEED_URL =
  process.env.VEKSNAP_UPDATE_FEED_URL ||
  "https://vek-snap.com/updates/latest.json";

/**
 * Read the installed app version.
 *
 * Primary source is the build-time-baked `VEKSNAP_APP_VERSION` (set in
 * next.config.ts from package.json). This is cwd-independent and works in the
 * packaged production server. The fs read is a defensive fallback for any
 * context where the env wasn't inlined (e.g. certain dev/tooling paths); during
 * `next dev` the cwd is this app root, so it still resolves correctly.
 */
export function getAppVersion(): string {
  const baked = process.env.VEKSNAP_APP_VERSION;
  if (baked && /^\d+\.\d+\.\d+/.test(baked)) return baked;
  try {
    const pkgPath = path.join(process.cwd(), "package.json");
    const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
    return typeof pkg.version === "string" ? pkg.version : "0.0.0";
  } catch {
    return "0.0.0";
  }
}

function parseSemver(v: string): [number, number, number] | null {
  const m = /^\s*v?(\d+)\.(\d+)\.(\d+)/.exec(String(v || ""));
  if (!m) return null;
  return [Number(m[1]), Number(m[2]), Number(m[3])];
}

/** True if `candidate` is a strictly newer SemVer than `base` (major.minor.patch). */
export function isNewerVersion(candidate: string, base: string): boolean {
  const a = parseSemver(candidate);
  const b = parseSemver(base);
  if (!a || !b) return false;
  for (let i = 0; i < 3; i++) {
    if (a[i] > b[i]) return true;
    if (a[i] < b[i]) return false;
  }
  return false;
}
