import { NextRequest, NextResponse } from "next/server";
import { exec } from "child_process";
import { promisify } from "util";
import { writeFile, readFile, mkdir } from "fs/promises";
import { existsSync } from "fs";
import path from "path";
import { getScratchDir } from "@/lib/scratch-dir";

const execAsync = (cmd: string) => promisify(exec)(cmd, { maxBuffer: 50 * 1024 * 1024, windowsHide: true });

export const dynamic = "force-dynamic";

// Install-local scratch, NOT os.tmpdir() (see src/lib/scratch-dir.ts), this stages copies
// of the user's media. Swept by the `appScratch` cleanup category.
const WORK_DIR = getScratchDir("metadata");

async function ensureDir() {
  if (!existsSync(WORK_DIR)) await mkdir(WORK_DIR, { recursive: true });
  return WORK_DIR;
}

/**
 * POST /api/extract-metadata
 * Extracts ComfyUI workflow/prompt metadata from MP4 or PNG files.
 * Returns { workflow?: object, prompt?: object }
 */
export async function POST(req: NextRequest) {
  try {
    const formData = await req.formData();
    const file = formData.get("file") as File;
    if (!file) return NextResponse.json({ error: "No file provided" }, { status: 400 });

    const dir = await ensureDir();
    const ext = path.extname(file.name).toLowerCase();
    const tmpPath = path.join(dir, `meta_${Date.now()}${ext}`);
    const buffer = Buffer.from(await file.arrayBuffer());
    await writeFile(tmpPath, buffer);

    let workflow: unknown = null;
    let prompt: unknown = null;

    if (ext === ".mp4" || ext === ".webm" || ext === ".mov") {
      // Use FFprobe to extract format tags
      try {
        const { stdout } = await execAsync(
          `ffprobe -v quiet -print_format json -show_format "${tmpPath}"`
        );
        const info = JSON.parse(stdout);
        const tags = info.format?.tags || {};

        // ComfyUI stores workflow and prompt as format-level tags
        if (tags.workflow) {
          try { workflow = JSON.parse(tags.workflow); } catch { workflow = tags.workflow; }
        }
        if (tags.prompt) {
          try { prompt = JSON.parse(tags.prompt); } catch { prompt = tags.prompt; }
        }
      } catch (err) {
        console.error("FFprobe error:", err);
      }
    } else if (ext === ".png") {
      // PNG files: ComfyUI stores metadata in tEXt chunks
      // We can extract them by reading the raw file and looking for the text chunks
      try {
        const data = await readFile(tmpPath);
        const pngStr = data.toString("latin1");

        // Look for "workflow" and "prompt" tEXt/iTXt chunks
        const extractPngText = (key: string): string | null => {
          // tEXt chunk: keyword\0text
          const marker = key + "\0";
          const idx = pngStr.indexOf(marker);
          if (idx === -1) return null;

          // Find the end of this chunk by looking for the next PNG chunk signature
          // Chunk structure: 4 bytes length + 4 bytes type + data + 4 bytes CRC
          // We look for the text content after the null separator
          const textStart = idx + marker.length;
          // Find the next IDAT, IEND, tEXt, or iTXt chunk as boundary
          let textEnd = pngStr.length;
          for (const sig of ["IDAT", "IEND", "tEXt", "iTXt", "zTXt"]) {
            const sigIdx = pngStr.indexOf(sig, textStart);
            if (sigIdx !== -1 && sigIdx < textEnd) {
              // Go back 4 bytes for the length field
              textEnd = sigIdx - 4;
            }
          }
          // Also trim any trailing CRC bytes (4 bytes before next chunk)
          const raw = pngStr.substring(textStart, textEnd);
          // Strip trailing non-JSON characters
          const trimmed = raw.replace(/[\x00-\x08\x0e-\x1f]+$/, "");
          return trimmed || null;
        };

        const workflowStr = extractPngText("workflow");
        const promptStr = extractPngText("prompt");

        if (workflowStr) {
          try { workflow = JSON.parse(workflowStr); } catch { /* ignore */ }
        }
        if (promptStr) {
          try { prompt = JSON.parse(promptStr); } catch { /* ignore */ }
        }
      } catch (err) {
        console.error("PNG metadata extraction error:", err);
      }
    }

    // Clean up temp file
    try { await import("fs/promises").then(fs => fs.unlink(tmpPath)); } catch { /* ignore */ }

    if (!workflow && !prompt) {
      return NextResponse.json(
        { error: "No ComfyUI metadata found in this file. Make sure it was generated by ComfyUI with metadata embedding enabled." },
        { status: 404 }
      );
    }

    return NextResponse.json({ workflow, prompt });
  } catch (err) {
    console.error("extract-metadata error:", err);
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Failed to extract metadata" },
      { status: 500 }
    );
  }
}
