"""SAM2 video mask tracking helper for Vek-Snap, fully offline.

Uses the official `facebookresearch/sam2` package bundled with the
ComfyUI-RMBG custom node. Given a source video and an initial mask
(painted manually or generated by SAM3) for frame 0, propagates the mask
across all video frames and emits a grayscale mask MP4 that the LTX 2.3
V2V Inpaint workflow can load via VHS_LoadVideoPath.

Pipeline:
  1. Decode source video -> directory of JPG frames (FFmpeg).
  2. Build SAM2VideoPredictor from local config + checkpoint (.safetensors
     or .pt). Will auto-download from `1038lab/sam2` on first use if missing.
  3. add_new_mask(frame_idx=0) using the supplied mask PNG.
  4. propagate_in_video() -> per-frame masks.
  5. Encode the masks into a grayscale MP4 (white = inpaint, black = keep)
     with the same fps + dimensions as the source video.

CLI:
    python sam2_track.py --video PATH --mask PATH --output PATH
                         [--model sam2.1_hiera_tiny] [--device cuda]
                         [--max-frames 0]

Emits a single JSON line on stdout for the Node host to parse.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
import traceback
from pathlib import Path


# --- Path discovery --------------------------------------------------------
def _resolve_sam2_pkg_root() -> Path:
    env = os.environ.get("VEKSNAP_SAM2_PKG_ROOT")
    if env and (Path(env) / "sam2").is_dir():
        return Path(env)
    here = Path(__file__).resolve()
    for parent in [here, *here.parents]:
        candidate = parent / "ComfyUI" / "custom_nodes" / "ComfyUI-RMBG" / "models"
        if (candidate / "sam2").is_dir():
            return candidate
    raise RuntimeError(
        "Could not locate the bundled SAM2 Python package "
        "(<install root>/ComfyUI/custom_nodes/ComfyUI-RMBG/models/sam2/). "
        "Set VEKSNAP_SAM2_PKG_ROOT if it lives elsewhere."
    )


SAM2_PKG_ROOT = _resolve_sam2_pkg_root()
if str(SAM2_PKG_ROOT) not in sys.path:
    sys.path.insert(0, str(SAM2_PKG_ROOT))

SAM2_CONFIGS_DIR = SAM2_PKG_ROOT / "sam2" / "configs"

# Mapping: model name -> (hydra config relative path inside SAM2_CONFIGS_DIR,
#                         checkpoint filename, fallback HF mirror url)
SAM2_MODELS = {
    "sam2.1_hiera_tiny": (
        "sam2.1/sam2.1_hiera_t.yaml",
        "sam2.1_hiera_tiny.safetensors",
        "https://huggingface.co/1038lab/sam2/resolve/main/sam2.1_hiera_tiny.safetensors",
    ),
    "sam2.1_hiera_small": (
        "sam2.1/sam2.1_hiera_s.yaml",
        "sam2.1_hiera_small.safetensors",
        "https://huggingface.co/1038lab/sam2/resolve/main/sam2.1_hiera_small.safetensors",
    ),
    "sam2.1_hiera_base_plus": (
        "sam2.1/sam2.1_hiera_b+.yaml",
        "sam2.1_hiera_base_plus.safetensors",
        "https://huggingface.co/1038lab/sam2/resolve/main/sam2.1_hiera_base_plus.safetensors",
    ),
    "sam2.1_hiera_large": (
        "sam2.1/sam2.1_hiera_l.yaml",
        "sam2.1_hiera_large.safetensors",
        "https://huggingface.co/1038lab/sam2/resolve/main/sam2.1_hiera_large.safetensors",
    ),
}


def _emit(payload: dict) -> None:
    print(json.dumps(payload, ensure_ascii=False))


def _find_ffmpeg() -> str:
    """Locate ffmpeg.exe: prefer ComfyUI's bundled binary, fall back to PATH."""
    for parent in Path(__file__).resolve().parents:
        for sub in ("ffmpeg/bin/ffmpeg.exe", "ffmpeg.exe"):
            cand = parent / sub
            if cand.is_file():
                return str(cand)
    found = shutil.which("ffmpeg")
    if found:
        return found
    raise RuntimeError("ffmpeg not found on PATH and no bundled copy found.")


def _resolve_checkpoint(model_name: str, candidate_dirs: list[Path]) -> Path:
    cfg_rel, ckpt_name, mirror_url = SAM2_MODELS[model_name]
    # Search candidate dirs first
    for d in candidate_dirs:
        p = d / ckpt_name
        if p.is_file():
            return p
        # Some users keep .pt versions
        pt = d / ckpt_name.replace(".safetensors", ".pt")
        if pt.is_file():
            return pt

    # Refuse to auto-download if offline mode is active (Vek-Snap core protection)
    if os.environ.get("HF_HUB_OFFLINE") == "1":
        raise RuntimeError(
            f"SAM2 checkpoint '{ckpt_name}' not found locally and system is in offline mode. "
            f"Place the checkpoint in one of: {[str(d) for d in candidate_dirs]} "
            f"or enable online mode in Vek-Snap settings to allow download."
        )

    # Auto-download into the first candidate dir (only when online mode is enabled)
    target_dir = candidate_dirs[0]
    target_dir.mkdir(parents=True, exist_ok=True)
    target = target_dir / ckpt_name
    print(f"[sam2_track] Downloading {ckpt_name} from {mirror_url}", file=sys.stderr)
    try:
        from torch.hub import download_url_to_file  # type: ignore
        download_url_to_file(mirror_url, str(target))
    except Exception as e:
        raise RuntimeError(
            f"Failed to download {ckpt_name} from {mirror_url}: {e}. "
            f"Manually place a SAM2 checkpoint in {target_dir} and retry."
        ) from e
    return target


def _load_state_dict(ckpt_path: Path):
    import torch  # type: ignore
    if ckpt_path.suffix == ".safetensors":
        from safetensors.torch import load_file  # type: ignore
        return load_file(str(ckpt_path))
    sd = torch.load(str(ckpt_path), map_location="cpu", weights_only=True)
    return sd.get("model", sd) if isinstance(sd, dict) else sd


def _build_predictor(model_name: str, ckpt_path: Path, device: str):
    """Mirror of build_sam2_video_predictor that loads weights ourselves so
    we can support both .safetensors and .pt checkpoints."""
    from hydra import initialize_config_dir, compose  # type: ignore
    from hydra.core.global_hydra import GlobalHydra  # type: ignore
    from hydra.utils import instantiate  # type: ignore
    from omegaconf import OmegaConf  # type: ignore

    cfg_rel, _, _ = SAM2_MODELS[model_name]

    if GlobalHydra.instance().is_initialized():
        GlobalHydra.instance().clear()
    initialize_config_dir(config_dir=str(SAM2_CONFIGS_DIR), version_base=None)

    overrides = [
        "++model._target_=sam2.sam2_video_predictor.SAM2VideoPredictor",
        "++model.sam_mask_decoder_extra_args.dynamic_multimask_via_stability=true",
        "++model.sam_mask_decoder_extra_args.dynamic_multimask_stability_delta=0.05",
        "++model.sam_mask_decoder_extra_args.dynamic_multimask_stability_thresh=0.98",
        "++model.binarize_mask_from_pts_for_mem_enc=true",
        "++model.fill_hole_area=8",
    ]
    cfg = compose(config_name=cfg_rel, overrides=overrides)
    OmegaConf.resolve(cfg)
    model = instantiate(cfg.model, _recursive_=True)

    sd = _load_state_dict(ckpt_path)
    missing, unexpected = model.load_state_dict(sd, strict=False)
    if missing:
        print(f"[sam2_track] Missing keys ({len(missing)}): {missing[:5]}...", file=sys.stderr)
    if unexpected:
        print(f"[sam2_track] Unexpected keys ({len(unexpected)}): {unexpected[:5]}...", file=sys.stderr)

    model.to(device).eval()
    return model


def _extract_frames(video_path: str, out_dir: Path, max_frames: int = 0) -> tuple[float, int, int, int]:
    """Decode video to numbered JPG frames; return (fps, n_frames, width, height)."""
    out_dir.mkdir(parents=True, exist_ok=True)
    ff = _find_ffmpeg()

    # Probe video for fps + size
    probe = subprocess.run(
        [ff, "-i", video_path, "-hide_banner"],
        stderr=subprocess.PIPE, stdout=subprocess.PIPE, encoding="utf-8", errors="ignore",
    )
    info = (probe.stderr or "") + (probe.stdout or "")

    fps = 24.0
    width = height = 0
    import re
    m_fps = re.search(r"(\d+(?:\.\d+)?)\s*fps", info)
    if m_fps:
        try: fps = float(m_fps.group(1))
        except ValueError: pass
    m_size = re.search(r"(\d{2,5})x(\d{2,5})", info)
    if m_size:
        width, height = int(m_size.group(1)), int(m_size.group(2))

    cmd = [ff, "-y", "-i", video_path]
    if max_frames > 0:
        cmd += ["-frames:v", str(max_frames)]
    cmd += ["-q:v", "2", "-start_number", "0", str(out_dir / "%05d.jpg")]
    subprocess.run(cmd, check=True, stderr=subprocess.PIPE, stdout=subprocess.PIPE)

    n = len(list(out_dir.glob("*.jpg")))
    if n == 0:
        raise RuntimeError(f"FFmpeg produced zero frames for {video_path}")
    return fps, n, width, height


def _encode_mask_video(masks_dir: Path, output_path: str, fps: float):
    """Encode the per-frame mask PNGs into a grayscale-on-black MP4."""
    ff = _find_ffmpeg()
    cmd = [
        ff, "-y", "-framerate", f"{fps:.6f}",
        "-i", str(masks_dir / "%05d.png"),
        "-c:v", "libx264", "-pix_fmt", "yuv420p",
        "-crf", "18",  # near-lossless to preserve mask edges
        "-vf", "format=gray,format=yuv420p",
        output_path,
    ]
    subprocess.run(cmd, check=True, stderr=subprocess.PIPE, stdout=subprocess.PIPE)


def run(video_path: str, mask_path: str, output_path: str,
        model_name: str = "sam2.1_hiera_tiny", device: str = "cuda",
        max_frames: int = 0) -> dict:
    import torch  # type: ignore
    import numpy as np  # type: ignore
    from PIL import Image  # type: ignore
    from contextlib import nullcontext

    if device == "cuda" and not torch.cuda.is_available():
        device = "cpu"
    if model_name not in SAM2_MODELS:
        raise RuntimeError(f"Unknown SAM2 model {model_name!r}. Choices: {list(SAM2_MODELS)}")

    # Resolve checkpoint location: prefer ComfyUI's standard locations
    candidate_dirs: list[Path] = []
    here = Path(__file__).resolve()
    for parent in here.parents:
        if (parent / "ComfyUI").is_dir():
            candidate_dirs.append(parent / "ComfyUI" / "models" / "sam2")
            break
    candidate_dirs.append(SAM2_PKG_ROOT.parent / "models" / "sam2")  # ComfyUI-RMBG/models/sam2

    ckpt_path = _resolve_checkpoint(model_name, candidate_dirs)

    workdir = Path(tempfile.mkdtemp(prefix="veksnap_sam2_"))
    frames_dir = workdir / "frames"
    masks_dir = workdir / "masks"
    masks_dir.mkdir(parents=True, exist_ok=True)
    try:
        # 1. Frames
        fps, n_frames, _w, _h = _extract_frames(video_path, frames_dir, max_frames)
        print(f"[sam2_track] {n_frames} frames @ {fps:.3f} fps", file=sys.stderr)

        # 2. Predictor
        predictor = _build_predictor(model_name, ckpt_path, device)

        # 3. Init state on the frame directory (SAM2 expects sorted JPGs)
        autocast_ctx = (
            torch.autocast(device_type=device, dtype=torch.bfloat16)
            if device == "cuda" else nullcontext()
        )
        with torch.inference_mode(), autocast_ctx:
            state = predictor.init_state(video_path=str(frames_dir))

            # 4. Add the initial mask at frame 0. SAM2 expects HxW bool tensor matching
            #    the *original* frame resolution (it'll resize internally).
            mask_img = Image.open(mask_path).convert("L")
            # Resize mask to first-frame size if needed
            first_frame = Image.open(sorted(frames_dir.glob("*.jpg"))[0])
            if mask_img.size != first_frame.size:
                mask_img = mask_img.resize(first_frame.size, Image.NEAREST)
            mask_arr = np.array(mask_img) > 127
            mask_t = torch.from_numpy(mask_arr.astype(np.uint8)).to(device)

            predictor.add_new_mask(state, frame_idx=0, obj_id=1, mask=mask_t)

            # 5. Propagate
            n_written = 0
            max_score = 0.0
            for frame_idx, obj_ids, mask_logits in predictor.propagate_in_video(state):
                # mask_logits: (num_objs, 1, H, W) - sigmoid > 0.5 = positive
                m = (mask_logits[0, 0] > 0.0).cpu().numpy().astype(np.uint8) * 255
                Image.fromarray(m, mode="L").save(masks_dir / f"{frame_idx:05d}.png")
                n_written += 1
                # Optional confidence proxy: average positive logit value
                pos = mask_logits[0, 0]
                if pos.numel():
                    s = float(pos[pos > 0].mean().item()) if (pos > 0).any() else 0.0
                    max_score = max(max_score, s)

        if n_written == 0:
            raise RuntimeError("SAM2 propagation wrote zero frames.")

        # 6. Encode mp4
        _encode_mask_video(masks_dir, output_path, fps)
        if not Path(output_path).is_file():
            raise RuntimeError(f"FFmpeg produced no output at {output_path}")

        return {
            "ok": True,
            "output": output_path,
            "device": device,
            "model": model_name,
            "checkpoint": str(ckpt_path),
            "fps": fps,
            "n_frames": n_written,
            "max_score": max_score,
        }
    finally:
        try: shutil.rmtree(workdir, ignore_errors=True)
        except Exception: pass


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--video", required=True)
    p.add_argument("--mask", required=True)
    p.add_argument("--output", required=True)
    p.add_argument("--model", default="sam2.1_hiera_tiny", choices=list(SAM2_MODELS))
    p.add_argument("--device", default="cuda")
    p.add_argument("--max-frames", type=int, default=0, dest="max_frames")
    args = p.parse_args()

    try:
        result = run(
            video_path=args.video,
            mask_path=args.mask,
            output_path=args.output,
            model_name=args.model,
            device=args.device,
            max_frames=args.max_frames,
        )
        _emit(result)
        return 0
    except RuntimeError as e:
        msg = str(e)
        _emit({
            "ok": False,
            "error": msg,
            "needs_setup": (
                "Could not locate" in msg or "checkpoint" in msg.lower()
                or "ffmpeg" in msg.lower()
            ),
        })
        return 1
    except Exception as e:
        _emit({
            "ok": False,
            "error": f"{type(e).__name__}: {e}",
            "trace": traceback.format_exc(),
        })
        return 2


if __name__ == "__main__":
    sys.exit(main())
